### ISSUE TITLE
check for blacklisted gcc versions fail

### ISSUE THREAD

**Issue by vicalro** [bisdn/rofl-core#46]
The check of version of gcc implemented in config/gcc.m4 depends on the command ```gcc -v```. In some cases this command is not giving the revision or patch number (e.g. 4.8.1) and only gives the release number (e.g. 4.8). This behaviour leads to overlook the actual gcc version.

**Comment by msune** [comment]
Is this for 0.6.0 final?

**Comment by vicalro** [comment]
As it is a bug fix I would propose to include it in 0.6.0.
The only possible matter I see are the dependencies with ```grep``` and ```awk```. If there are no objections on that I can do the merge
